
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 02 10:50:44 COT 2009
//----------------------------------------------------

package T5;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 30;
  public static final int LIBRERIA = 37;
  public static final int GUIONBAJO = 29;
  public static final int MENSAJE = 21;
  public static final int ENTERO = 22;
  public static final int SI = 4;
  public static final int DECREMENTADOR = 28;
  public static final int ENTONCES = 11;
  public static final int PUNTOCOMA = 33;
  public static final int TIPOBOOLEANO = 7;
  public static final int PRINCIPAL = 3;
  public static final int SINO = 12;
  public static final int OPCION = 16;
  public static final int MIENTRAS = 17;
  public static final int HACERMIENTRAS = 5;
  public static final int CONDICIONAL = 9;
  public static final int COMPARADORES = 26;
  public static final int EOF = 0;
  public static final int INCREMENTADOR = 27;
  public static final int LDERECHO = 32;
  public static final int TIPOCHARS = 6;
  public static final int error = 1;
  public static final int COMA = 35;
  public static final int BOOLS = 34;
  public static final int CADENA = 10;
  public static final int OPERADORES = 25;
  public static final int TIPONUMBER = 8;
  public static final int RETORNA = 18;
  public static final int ESCRIBE = 19;
  public static final int PIZQUIERDO = 36;
  public static final int PORCADA = 14;
  public static final int REAL = 23;
  public static final int EN = 15;
  public static final int NUEVO = 2;
  public static final int VARIABLE = 39;
  public static final int PDERECHO = 38;
  public static final int ASIGNADOR = 24;
  public static final int LIZQUIERDO = 31;
  public static final int PARA = 13;
  public static final int LEE = 20;
}

